content/apps/zelty/en/connect-hubrise.md, content/apps/zelty/en/faq.md, content/apps/zelty/en/map-ref-codes.md, content/apps/zelty/en/orders.md, content/apps/zelty/en/overview.md, content/apps/zelty/en/troubleshooting.md, content/apps/zelty/en/zelty-terms.md
@antmonnier, please double check and publish.
=> Zelty update: Antoine's review feedback implementation

content/base/en/menu-footer.yaml, content/base/fr/menu-footer.yaml, content/en/branding.md, content/fr/branding.md, content/fr/faq.md, src/styles/components/faq.scss
@antmonnier, branding pages are ready for review and deployment. 
I made links in the footer for it. 
Note that an issue was created to fix the h5 and quote spacing issues.
=> Jw 20200917 branding pages

content/apps/pixelpoint-bridge/en/understanding-logs.md, content/apps/pixelpoint-windows-api/en/understanding-logs.md
- Revert changes to wrong PixelPoint documentation
- Add tips, charges, and discounts in PixelPoint Bridge
=> PixelPoint update

content/developers/en/integration-guide.md
Comments directly within the text marked by [comment]: # (MY COMMENT)
=> integration-guide-feedback

content/developers/en/quick-start.md
A few corrections and [Comments] within the text. 
I let you review, make the needed changes.
Additional feedback: 
If I understand, you are suggesting here to send request from an inner system. Is that as efficient as using a complex menu on LivePepper to send orders and discounts?
=> quick-start feedback

content/apps/pixelpoint-bridge/en/user-interface.md
Clicking should not be bold according to styleguide.
=> [PixelPoint] User Interface

content/developers/en/quick-start.md
- Explain that access token does not expire
- Fix typos
Closes #197
=> Quick start: access token note

content/contributing/en/style-guide.md
Add "the" as one of the words to not capitalise.
=> Update capitalisation section

content/docs/en/connections.md, content/docs/en/overview.md, content/docs/en/usage-plan.md, content/docs/faqs/fr/formule-gratuite-quota-depasse-ce-qui-se-passe.md, content/docs/faqs/fr/payer-la-premiere-facture.md, content/docs/faqs/fr/reactiver-un-compte-suspendu.md, content/docs/faqs/fr/verifier-connexion-entre-mon-systeme-et-hubrise.md, content/docs/fr/catalogues.md, content/docs/fr/comment-demarrer.md, content/docs/fr/comptes.md, content/docs/fr/connexions.md, content/docs/fr/developpeur.md, content/docs/fr/donnees.md, content/docs/fr/listes-clients.md, content/docs/fr/paiement.md, content/docs/fr/permissions.md, content/docs/fr/points-de-vente.md, content/docs/fr/presentation-generale.md, content/docs/fr/profil-mot-de-passe.md, content/docs/fr/tableau-de-bord.md, content/docs/fr/utilisation-formule.md
@janaina-wittner Pour info, j'ai commencé ma review dans un PR séparé pour tracer les changements.
=> [Help pages] Translation review

content/apps/myorderbox/en/faqs.md, content/apps/myorderbox/faqs/en/customization.yaml, content/apps/myorderbox/faqs/en/migrating-from-deliverect.md
@janaina-wittner Can you please review?
=> [MyOrderBox] Migration from Deliverect

APPS-TEMPLATE/en/food-ordering-platforms.md, APPS-TEMPLATE/fr/plateformes-livraison-repas.md, content/apps/epos-technologies/en/food-ordering-platforms.md, content/apps/etakeaway-max/en/food-ordering-platforms.md, content/apps/french-caisse/en/overview.md, content/apps/kezia/fr/plateformes-livraison-repas.md, content/apps/leo2/fr/plateformes-livraison-repas.md, content/apps/lightspeed-restaurant/en/food-ordering-platforms.md, content/apps/myorderbox/en/food-ordering-platforms.md, content/apps/nestor/fr/plateformes-livraison-repas.md, content/apps/orderlord/en/food-ordering-platforms.md, content/apps/pos-helper/fr/plateformes-livraison-repas.md, content/apps/ultimapos/fr/plateformes-livraison-repas.md
Supersedes and replaces #646, #641, #645
=> [Food platforms pages] Update and enforce the template across all apps

content/apps/deliveroo/en/configuration.md, content/apps/deliveroo/en/connect-hubrise.md, content/apps/deliveroo/en/push-catalog.md, content/apps/deliveroo/en/receive-orders.md, content/apps/deliveroo/en/user-interface.md, content/apps/foodpanda/en/connect-hubrise.md, content/apps/foodpanda/en/user-interface.md, content/apps/just-eat-takeaway/en/configuration.md, content/apps/just-eat-takeaway/en/connect-hubrise.md, content/apps/just-eat-takeaway/en/receive-orders.md, content/apps/just-eat-takeaway/en/user-interface.md, content/apps/lightspeed-restaurant/en/configuration.md, content/apps/lightspeed-restaurant/en/pull-catalog.md, content/apps/lightspeed-restaurant/en/user-interface.md, content/apps/pixelpoint-bridge/en/user-interface.md, content/apps/shopify/en/connect-hubrise.md, content/apps/shopify/en/pull-orders.md, content/apps/shopify/en/user-interface.md, content/apps/uber-eats/en/configuration.md, content/apps/uber-eats/en/connect-hubrise.md, content/apps/uber-eats/en/push-catalog.md, content/apps/uber-eats/en/receive-orders.md, content/apps/uber-eats/en/user-interface.md, content/apps/woocommerce/en/connect-hubrise.md, content/apps/woocommerce/en/pull-orders.md, content/apps/woocommerce/en/user-interface.md
@janaina-wittner FYI, this PR applies your changes in Just Eat Flyt EN to the EN content of the other bridges.
=> Apply PR #660 changes to other bridges

content/apps/just-eat-flyt/fr/connexion-hubrise.md
@janaina-wittner, this PR will be used to update the translation once Antoine has reviews the Just Eat Flyt EN updates I made.
=> [JUST EAT FLYT] translation update

APPS-TEMPLATE/en/overview.md, APPS-TEMPLATE/fr/presentation-generale.md
@antmonnier, tiny template changes. 
Ready for merge.
=> [TEMPLATE UPDATE] tiny template update

content/apps/locatouch/fr/presentation-generale.md
=> [LOCA TOUCH] typo fix

content/apps/zuplyit/en/overview.md
@antmonnier, I made a few changes based on Armando's feedback. It's ready for publication.
=> [ZUPLYIT] Tiny update to overview page

content/en/apps.yaml, content/fr/apps.yaml
@antmonnier, removed a few Integration in progress from our apps page.
=> [APPS PAGE] tiny fixes

content/apps/jalia/fr/presentation-generale.md, content/apps/popina/fr/presentation-generale.md
Jalia can push a menu to HubRise. cc @janaina-wittner
=> [Popina/Jalia] Overview update

content/apps/deliveroo/en/connect-hubrise.md, content/apps/just-eat-flyt/en/connect-hubrise.md, content/apps/just-eat-takeaway/en/connect-hubrise.md, content/apps/uber-eats/en/connect-hubrise.md
@antmonnier This is ready for publication.
=> [PLATFORMS] UE, Deliveroo, JE and Flyt connection page review

content/apps/adipos/fr/plateformes-livraison-repas.md
=> [AdiPOS] Food platforms

content/apps/smood/en/overview.md
This is the overview page for Smood based on the current French version. I'll keep this PR separate from the other pages, in case you want to review and publish this page while I work on the rest of the content.
=> [Smood] Overview page in English

content/apps/lightspeed-restaurant/en/faqs.md, content/apps/lightspeed-restaurant/faqs/en/update-lightspeed-restaurant-bridge.md
=> [LIGHTSPEED] FAQ EN localisation - Take advantage of integration updates

content/apps/jalia/en/overview.md, content/apps/popina/en/overview.md, content/apps/popina/fr/presentation-generale.md
=> [JALIA & POPINA] Overview translation

content/apps/deliveroo/en/faqs.md, content/apps/deliveroo/en/overview.md, content/apps/deliveroo/en/pull-catalog.md, content/apps/deliveroo/en/receive-orders.md, content/apps/deliveroo/faqs/en/connect-from-deliveroo-back-office.md, content/apps/deliveroo/faqs/en/find-deliveroo-restaurant-id.md, content/apps/deliveroo/faqs/fr/connect-from-deliveroo-back-office.md, content/apps/deliveroo/faqs/fr/deliveroo-tabletless.md, content/apps/deliveroo/faqs/fr/find-deliveroo-restaurant-id.md, content/apps/deliveroo/fr/configuration.md, content/apps/deliveroo/fr/connect-hubrise.md, content/apps/deliveroo/fr/faqs.md, content/apps/deliveroo/fr/map-ref-codes.md, content/apps/deliveroo/fr/overview.md, content/apps/deliveroo/fr/pull-catalog.md, content/apps/deliveroo/fr/push-catalog.md, content/apps/deliveroo/fr/receive-orders.md, content/apps/deliveroo/fr/terminology.md, content/apps/deliveroo/fr/troubleshooting.md, content/apps/deliveroo/fr/user-interface.md
TODO: the content within `<InlineImage>` should not be translatable.
=> [Deliveroo] FR translation

content/apps/orderline/en/launch-orderline.md, content/apps/orderline/en/manage-orders.md, content/apps/orderline/en/settings.md, content/apps/orderline/en/user-interface.md, content/apps/orderline/fr/launch-orderline.md, content/apps/orderline/fr/manage-orders.md, content/apps/orderline/fr/user-interface.md
=> [OrderLine] Corrections

src/components/DocumentationContainer/Styles.ts
=> Collapse margins in multi-level lists

content/apps/catalog-manager/en/launch-catalog-manager.md
Fix a couple of missing periods at the end of the sentences.
=> [Catalog Manager] Add missing periods

src/layouts/Apps/Nav/index.tsx
https://github.com/HubRise/website/issues/895
=> [APPS] Search autofocus on load

content/apps/woocommerce/en/configuration.md
Mention of "Prestashop" instead of "WooCommerce" at the bottom of the page
=> Small update configuration.md 

content/apps/deliveroo/fr/connect-hubrise.md, content/apps/just-eat-flyt/fr/connect-hubrise.md, content/apps/just-eat-takeaway/fr/connect-hubrise.md, content/apps/lightspeed-restaurant/fr/connect-hubrise.md, content/apps/orderline/en/connect-hubrise.md, content/apps/orderline/fr/connect-hubrise.md, content/apps/popina/fr/connect-hubrise.md, content/apps/smood/fr/connect-hubrise.md, content/apps/tickncook/en/connect-hubrise.md, content/docs/faqs/fr/check-connection-between-my-system-and-hubrise.md, content/docs/faqs/fr/check-if-i-already-have-a-user-profile-in-hubrise.md, content/docs/faqs/fr/connect-multiple-instances-same-app.md, content/docs/faqs/fr/create-a-user-profile-for-another-person.md, content/docs/faqs/fr/create-an-account-for-another-business.md, content/docs/faqs/fr/pay-first-invoice.md, content/docs/faqs/fr/reactivate-suspended-account.md, content/docs/faqs/fr/recover-lost-password-in-hubrise.md, content/docs/faqs/fr/stop-paying-subscription.md, content/docs/fr/connections.md, content/docs/fr/get-started.md, content/docs/fr/payment.md, content/docs/fr/permissions.md, content/docs/fr/profile-password.md
=> Remove ?locale= from links

src/components/DocumentationContainer/Styles.ts
=> Documentation: fix image vertical spacing in lists

content/apps/pixelpoint-windows-api/en/overview.md, content/en/apps.yaml, content/fr/apps.yaml
Apps page update with **Title: PAR** and inclusion of Catalog push in overview page. 
Also a tiny update to Takeaway **Title: Just Eat Takeaway** to ease search in our Apps page.
You can merge these straight away, there is nothing in this PR.
=> [PIXEL POINT] tiny update

content/apps/lightspeed-restaurant/en/faqs.md, content/apps/lightspeed-restaurant/faqs/en/migrate-from-deliverect.md, content/apps/lightspeed-restaurant/faqs/en/migrating-from-deliverect.md, content/apps/lightspeed-restaurant/faqs/fr/migrate-from-deliverect.md, content/apps/lightspeed-restaurant/fr/faqs.md
@janaina-wittner I've just restored the page we removed in 2022, and made little content changes. I've also uploaded the FR translation.
=> [Lightspeed] Restore Deliverect migration page

content/apps/quick-up/en/connect-hubrise.md, content/apps/quick-up/en/customization.yaml, content/apps/quick-up/en/overview.md, content/apps/quick-up/en/terminology.md, content/apps/quick-up/fr/customization.yaml, content/apps/quick-up/fr/overview.md, content/en/apps.yaml, content/fr/apps.yaml
Quick Up changed to QUICK UP as asked by the editor
Corwdin fixed too.
Ready for merge
=> [QUICK UP] name capitalised as asked

content/apps/eatself/en/overview.md, content/apps/eatself/fr/overview.md
Clyo systems asked for two additional features to be included in the overview page. 
Ready for Merge.
=> [EATSELF] feature inclusion

APPS-TEMPLATE/en/overview.md, APPS-TEMPLATE/fr/overview.md
@antmonnier; tiny updates, ready for merge.
=> [TEMPLATE] self-ordering kiosk and content
